config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :users, only: [:show, :index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    
    validates :first_name, presence: true, 
                            length: { minimum: 3, maximum: 20 }
    validates :last_name, presence: true,
                            length: { minimum: 3, maximum: 20 }
    validates :user_name, presence: true, 
                            length: { minimum: 3, maximum: 20 }, 
                            uniqueness: { case_sensitive: false }
    validates :display_name, presence: true, 
                            length: { minimum: 6, maximum: 20 }
    validates :major, presence: true
    validates :tutor_major, presence: true
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                            uniqueness: { case_sensitive: false },
                            format: { with: VALID_EMAIL_REGEX }
    validates :password, presence: true,
                            length: { minimum: 6, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # redirect_to posts_path if logged_in?
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    
    def show
    end
    
    def index
        @users = User.all
    end
    
    def new
        @user = User.new
    end
    
    def edit
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Profile was created successfully."
            redirect_to @user
        else
            render 'new'
        end
    end
    
    def update
        if @user.update(user_params)
            flash[:notice] = "The profile was updated successfully."
            redirect_to @user
        else
            render 'edit'
        end
    end
    
    def destroy
        @user.destroy
        redirect_to users_path
    end
    
    private

    def set_user
        @user = User.find(params[:id])
    end
    
    def user_params
        params.require(:user).permit(:first_name, :last_name, :user_name, :display_name,
            :gender, :email, :description, :major, :tutor_major)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindTutor</title>
    
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is ABOUT page</h1>

app/views/pages/home.html.erb
<h1>This is HOME page</h1>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_tag user_path(@user), :method => :put, :class => 'form' do %>
    <div class="form-group">
        <%= label :user, :first_name, 'First Name', :class => 'col-form-label' %>
        <%= text_field :user, :first_name, :class => 'form-control' %>
        
        <%= label :user, :last_name, 'Last Name', :class => 'col-form-label'  %>
        <%= text_field :user, :last_name, :class => 'form-control' %>
      
        <%= label :user, :gender, 'Gender', :class => 'col-form-label' %>
        <%= select :user, :gender, ['Male', 'Female', 'Unknown'], {}, {:class => 'form-control col-1'} %>
      
        <%= label :user, :user_name, 'User Name', :class => 'col-form-label' %>
        <%= text_field :user, :user_name, :class => 'form-control' %>
      
        <%= label :user, :display_name, 'Display Name', :class => 'col-form-label' %>
        <%= text_field :user, :display_name, :class => 'form-control' %>
        
        <%= label :user, :email, 'Email', :class => 'col-form-label' %>
        <%= text_field :user, :email, :class => 'form-control' %>
      
        <%= label :user, :major, 'Major', :class => 'col-form-label' %>
        <%= text_field :user, :major, :class => 'form-control' %>
      
        <%= label :user, :tutor_major, 'Tutor Major', :class => 'col-form-label' %>
        <%= text_field :user, :tutor_major, :class => 'form-control' %>
      
        <%= label :user, :description, 'Self Description', :class => 'col-form-label' %>
        <%= text_field :user, :description, :class => 'form-control' %>
      <br/>
      <%= submit_tag 'Edit', :class => 'btn btn-success' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<% if @user.errors.any? %>
    <h2>The following errors prevented profile from being created</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>User Name</th>
            <th>Display Name</th>
            <th>Gender</th>
            <th>Major</th>
            <th>Tutor Major</th>
            <th>Email</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.user_name %></td>
                <td><%= user.display_name %></td>
                <td><%= user.gender %></td>
                <td><%= user.major %></td>
                <td><%= user.tutor_major %></td>
                <td><%= user.email %></td>
                <td><%= user.description %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1>Build Your Profile</h1>

<% if @user.errors.any? %>
    <h2>The following errors prevented profile from being created</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_tag users_path, :class => 'form' do %>
    <div class="form-group">
        <%= label :user, :first_name, 'First Name', :class => 'col-form-label' %>
        <%= text_field :user, :first_name, :class => 'form-control' %>
        
        <%= label :user, :last_name, 'Last Name', :class => 'col-form-label'  %>
        <%= text_field :user, :last_name, :class => 'form-control' %>
      
        <%= label :user, :gender, 'Gender', :class => 'col-form-label' %>
        <%= select :user, :gender, ['Male', 'Female', 'Unknown'], {}, {:class => 'form-control col-1'} %>
      
        <%= label :user, :user_name, 'User Name', :class => 'col-form-label' %>
        <%= text_field :user, :user_name, :class => 'form-control' %>
      
        <%= label :user, :display_name, 'Display Name', :class => 'col-form-label' %>
        <%= text_field :user, :display_name, :class => 'form-control' %>
        
        <%= label :user, :email, 'Email', :class => 'col-form-label' %>
        <%= text_field :user, :email, :class => 'form-control' %>
      
        <%= label :user, :major, 'Major', :class => 'col-form-label' %>
        <%= text_field :user, :major, :class => 'form-control' %>
      
        <%= label :user, :tutor_major, 'Tutor Major', :class => 'col-form-label' %>
        <%= text_field :user, :tutor_major, :class => 'form-control' %>
      
        <%= label :user, :description, 'Self Description', :class => 'col-form-label' %>
        <%= text_field :user, :description, :class => 'form-control' %>
      <br/>
      <%= submit_tag 'Submit', :class => 'btn btn-success' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
  
<% end %>

app/views/users/show.html.erb
<h1>User Profile</h1>
<p><strong>First Name: <%= @user.first_name %></strong></p>
<p><strong>Last Name: <%= @user.last_name %></strong></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Return', users_path %>